src/quality/pology/upstream/false-friends.rules

Added valid subdirectives for "introduce" and " produce" to cancelling false positives for Gimp

Cancel false positives for Gimp

---

cfg/projects/Mozilla.json

Please note: This patch has not been tested.
I was not sure what kind of "type" had to be used. I assumed "file", as seen in other projects.

Migrating Mozilla projects to Pontoon

---

cfg/projects/xfe.json

_xfe_ file manager does not provide a git repository, but Debian maintains its own.
Current xfe translation to Catalan is not very good at this moment, but I plan to improve it soon.

Add xfe file manager

---

cfg/projects/WindowsCalculator.json

Com que no sé si el sistema suporta el format resw (no he trobat exemples al repositori), ho poso de moment al meu repositori intermedi. Jo he fet servir [resx2po](https://github.com/pereorga/software-translations/blob/master/calc/generate.sh), que està al Translate Toolkit.
Aquest projecte tot i ser de Microsoft, té llicència MIT. És especialment interessant per les traduccions d'unitats.

Windows Calculator: nou projecte

---

cfg/projects/WinMerge.json

Actualitzo l'URL al repositori correcte (l'altre és un fork que ja no s'actualitza)
No he vist res malament al fitxer, pel que veig és un fitxer gettext vàlid, msgattrib funciona.
No ho he pogut provar (estic en mac, sense un linux a prop) però no veig res que podria fer-ho fallar, així que el torno a habilitar.

WinMerge: actualitzo URL i torno a habilitar

---

cfg/projects/RawTherapee.json

Crec que és un projecte que ens interessa tenir a les memòries (i a l'informe d'errors).
El poso a través del repositori intermedi. Fa servir fitxers pseudo-csv (més detalls a https://github.com/pereorga/software-translations/blob/master/rawtherapee/generate.sh)

RawTherapee: nou projecte

---

README.md

L'ordre d'exemple s'executa correctament: `./builder.py -p Abiword`
L'ordre pip encara dona un error en instal·lar els requisits, però no he trobat com resoldre-ho:
```
$ pip install -r requirements.txt
Requirement already satisfied: polib==1.1.1 in /opt/homebrew/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (1.1.1)
Collecting pystache
Using cached pystache-0.6.0-py3-none-any.whl
Requirement already satisfied: peewee==3.14.8 in /opt/homebrew/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (3.14.8)
Collecting hunspell
Using cached hunspell-0.5.5.tar.gz (34 kB)
Preparing metadata (setup.py) ... done
Collecting phply
Using cached phply-1.2.6-py2.py3-none-any.whl (74 kB)
Collecting translate-toolkit==3.3.4
Using cached …
```

docs(README): provide installation steps on macOS

---

cfg/projects/MediaWiki.json

mediawiki.po no baixa perquè és massa gros (surt com a error al log), i ara la majoria d'ell ja està inclòs en fitxers més petits.
mediawiki-exif és un altre fitxer interessant

MediaWiki: suprimeixo mediawiki.po (és massa gros) i afegeixo mediawiki-exif

---

cfg/projects/CKEditor.json

Aquest projecte ja havia existit a les memòries (a través de Transifex) però es va suprimir.
Aquesta PR funciona, tot i que el procés es torna una mica boig intentant convertir els fitxers amb extensió TS (TypeScript) a PO, quan en realitat el que hauria de fer només és importar tots els fitxers PO existents. Sembla que el problema és que s'executa la funció _convert_ts_files_to_po, fins i tot encara que li hagi indicat un patró que inclogui només els fitxers .po.
Potser, tot i que el "type" sigui "git", s'hauria de poder indicar el format dels fitxers d'origen. En general, els repositoris només contindran un sol format (Gettext, TS, etc) i es podria especificar manualment. Ara bé, m'imagino que hi pot haver projectes que depenguin en el comportament actual. L'extensió ts per TypeScript …

CKEditor: nou projecte

---

src/builder/convertfiles.py

When filename (input or output) has spaces, xliff2po command returns an error. This fix solves this error.

Fix error when filename has spaces

---

cfg/projects/Clementine.json

Afegeixo també les traduccions de [Strawberry Music Player](https://www.strawberrymusicplayer.org/), un fork de Clementine. Potser més endavant se'n pot esborrar un o separar els projectes en 2 fitxers, ara per ara tots dos semblen mantinguts.

Clementine: new project

---

README.md

This fixes installation on Ubuntu 22.04

docs(README): call pip3 rather than pip

---

cfg/projects/SuperTux.json
cfg/projects/VLC.json

Afegeixo fitxers de traducció addicionals.
En el cas de VLC, afegeixo el projecte VLMC. M'agradaria incloure les traduccions d'Android i iPhone, però no estic segur que suportem els seus formats (.strings i strings.xml):
- https://code.videolan.org/videolan/vlc-android/-/tree/master/application/resources/src/main/res/values-ca
- https://code.videolan.org/videolan/vlc-ios/-/tree/master/Resources/ca.lproj
En el cas del SuperTux, afegeixo traduccions dels nivells. Si de Transifex en venien més, no entenc d'on podien sortir, potser de versions antigues.

Add additional files for VLC and SuperTux projects

---

cfg/projects/WinSCP.json

```
$ python3 builder.py -p"WinSCP"
Translation memory builder version 0.1
Use --help for assistance
Projects defined in the projects configuration directory 226
S'està clonant a «_git»...
remote: Enumerating objects: 219, done.
remote: Counting objects: 100% (219/219), done.
remote: Compressing objects: 100% (200/200), done.
remote: Total 219 (delta 34), reused 120 (delta 18), pack-reused 0
S'estan rebent objectes: 100% (219/219), 823.84 KiB | 3.39 MiB/s, fet.
S'estan resolent les diferències: 100% (34/34), fet.
Projects. Added into tots-tm.po a total of 17808 words from 1 projects. Skipped 0 project(s) with 0 words due to license incompatibility
Projects clean up:0
processing 1 files...
[###########################################] 100%
processing 1 files... …
```

WinSCP: new project

---

cfg/projects/DjangoCMS.json
cfg/projects/GNUSocial.json

De GNUSocial surten menys cadenes, però sembla que siguin totes. El projecte sembla força inactiu de totes maneres

refactor: move DjangoCMS and GNUSocial from Transifex

---

cfg/projects/WireGuard.json
src/builder/convertfiles.py

- Faltaria la part Windows, que fa servir fitxers INI potser personalitzats: https://github.com/WireGuard/wireguard-windows/tree/master/locales/
- He provat la integració Crowdin i en aquest cas m'ha semblat que no ajudava en res
- En el cas d'Apple, he hagut de considerar el cas que el directori de la llengua original sigui "Base.lproj" en comptes de "en.lproj". Diria que ho he vist a més llocs. No estic segur que el codi sigui òptim, però funciona

WireGuard: new project

---

cfg/projects/Stooa.json

Fa servir diversos JSON monolingües i 2 fitxers YAML, però amb noms personalitzats.
https://github.com/pereorga/software-translations/blob/master/stooa/generate.sh
Comentat a https://github.com/Softcatala/translation-memory-tools/issues/287#issuecomment-1674005491

Stooa: new project

---

cfg/projects/RocketChat.json
src/builder/convertfiles.py

He afegit un nou nom de fitxer JSON per defecte (ca.i18n.json).
El procés és una mica lent, crec que pel fet que intenta traduir centenars de fitxers TypeScript:
```
processing 1 files...
[###########################################] 100%
RocketChat project. 4706 translated strings, words 28768
Translation memory for all projects: 4706 translated strings, words 28768
Time used to build memories: 0:08:22.714176
```

RocketChat: new project

---

cfg/projects/VLC.json

Closes #263. Temporalment, a l'espera de https://github.com/translate/translate/issues/4989 (que veig poc probable). Tampoc és segur que puguem generalitzar-ho fàcilment, doncs la codificació pot variar per fitxer i no per projecte.
Mitiga també #281, encara que en aquest cas no sigui significatiu (només 3 cadenes).
https://github.com/pereorga/software-translations/blob/master/vlc-ios/generate.sh
També arregla la importació de VLMC, pel fet de treure l'espai al nom del projecte. No estic segur si això de l'espai és una regressió que afecta a més projectes, o potser només em passa a mi al Mac.

VLC: add iOS translation

---

cfg/projects/JitsiMeet.json
src/builder/convertfiles.py

Closes #287
De fet ja hi era, però estava desactivat (apuntava a un Weblate inexistent).
Perquè funcioni he d'afegir un nou nom de fitxer JSON i deixar el nom del projecte sense espais.

Jitsi Meet: new project

---

cfg/projects/GodotEngine.json

Arregla el problema d'importació reportat a https://static.softcatala.org/memories/builder-error.log.
Entenc que al fileset millor no tenir-hi espais.

Godot Engine: fix import

---

cfg/projects/KDE.json

This new cfg file for KDE will download all Catalan translations from KDE branches (trunk-KF5 & trunk-KF6; stable is included in trunk-KF5). Now, we will get about 3.278.000 words.

KDE project: add new version (KF6)

---

cfg/projects/Elk.json

Per algun motiu sembla que no importa cap cadena. En canvi, els fitxers https://github.com/elk-zone/elk/tree/main/locales se'm converteixen correctament amb json2po

Draft: Elk: new project

---

cfg/projects/OrganicMaps.json

Resulta que no cal convertir els fitxers font (Twine) si ja s'incorporen les cadenes de les aplicacions mòbils

Organic Maps: remove files with duplicated strings

---

cfg/projects/Keycloak.json

Crec que hi ha un bug i el `pattern` no delimita bé el camí, important cadenes dels directoris superiors (HomeAssistant). No sé si és només al meu Mac, però no és específic d'aquesta PR, també em passa a altres projectes (p. ex. OpenEmu). Si fos així, potser estaria important cadenes duplicades.

Keycloak: new project

---

cfg/projects/LuminaDesktop.json

El repositori https://github.com/trueos/lumina-i18n.git està arxivat des de 2018.

Lumina Desktop: move to new repos

---

cfg/projects/BleachBit.json

Sembla que la solució més robusta seria https://github.com/izimobil/polib/issues/148. Es pot tornar a on era quan ho arreglin, o si mai arreglen el fitxer del BleachBit.

BleachBit: move to custom repo and update license

---

cfg/projects/AnnasArchive.json

No és accessible (depenent de l'ISP, suposo)
He trobat el mirror https://software.annas-archive.se/AnnaArchivist/annas-archive/-/raw/main/allthethings/translations/ca/LC_MESSAGES/messages.po, però veig que el fitxer és monolingüe (fa servir etiquetes internes com a identificador, en comptes de les cadenes angleses).

Anna's Archive: disable project

---

cfg/projects/Bitwarden.json
src/builder/convertfiles.py

Adds 3895 translated strings (28677 words)

Bitwarden: new project

---

cfg/projects/SuperTux.json

SuperTux had removed all translations for all levels (https://github.com/SuperTux/supertux/commit/c48ff960efc80407f6b09c2a2924f91d1a8da7f7), so we need to remove Catalan levels to avoid download them

SuperTux: remove missing levels

---

cfg/projects/MicrosoftTerminology.json

Skype will be retired soon, but the translation can still be useful.

Skype: new project

---

src/builder/fileset.py

If a project's fileset contains a translation file which is a symlink, but the symlink's target file is removed (because it does not match the fileset's pattern), the symlink breaks. We rely on `os.path.exists(path)` to remove unnecessary files, but this function returns `False` if the file is a broken symlink [[1](https://docs.python.org/3/library/os.path.html#os.path.exists)]. As a result, broken symlinks are not removed and we get a bunch of warnings when building certain TMs (observed in the MetaBrainz project (#440).
This changes the function to `os.path.lexists(path)` instead, which does return `True` for broken symlinks [[2](https://docs.python.org/3/library/os.path.html#os.path.exists)] and allows the TM builder to properly remove them.

Fix: Remove broken symlinks when building filesets
