cfg/projects/Mozilla.json
With a recent Pootle update, there have been some changes in URLs.
=> Updated URLs for Mozilla projects

requirements.txt
=> requirements: add missing dependencies

cfg/projects/iDEditor.json
Not sure if it matters as it's currently disabled.
=> idEditor: fix project file

cfg/projects/Recalbox.json
=> Add Recalbox - EmulationStation

README.rst
Still not complete, I'm getting many 'sh: 1: a2po: not found' messages.
=> README: Try to add installation instructions on Debian

cfg/projects/Mozilla.json, source-pos/mozilla/ca.focus-for-android.tmx, source-pos/mozilla/ca.focus-for-ios.tmx
I'm not sure whether I had to add the local files as TMX or PO. I added them as TMX.
=> Adding Mozilla static memories

cfg/projects/drawio.json
=> Add draw.io

cfg/projects/GrubCustomizer.json
=> Grub Customizer: new project

cfg/projects/Drupal.json
Actualitzo a les noves versions.
=> Drupal: update core and contrib

cfg/projects/AsteroidOS.json, cfg/projects/SimpleMobileTools.json
Configuration file for new project Simple Mobile Tools
=> New project Simple Mobile Tools

cfg/projects/Solus.json
Updated URL for budgie-desktop translation
=> Updated Solus project

cfg/projects/MuseScore.json
=> Update URL for MuseScore project files

cfg/projects/Askbot.json, cfg/projects/Django.json, cfg/projects/Mixxx.json
Changed the Transifex downloads for Askbot, Django and Mixxx translations that are not working by Github downloads
=> Updated some Transifex projects to Github

cfg/projects/Drupal.json
- Actualitza a Drupal 10
- Actualitza a Webform 6
- Passa a utilitzar fitxers **.X** sempre, per obtenir la versió més nova
- Passa a utilitzar els URL del directori /all/, per fer el manteniment més simple
=> Drupal: actualitza a les últimes versions (core/contrib)

cfg/projects/HandBrake.json
L'he traduït recentment. Espero l'informe d'errors per crear les traduccions pel Mac i Windows (que crec que no van amb Gettext)
=> HandBrake: nou projecte

cfg/projects/Phabricator.json
Suprimeixo el fitxer que falla.
=> Phabricator: remove phabricator group, as it does not download

cfg/projects/MediaWiki.json
Aprofito per suprimir la baixada de totes les extensions, que donava error a https://static.softcatala.org/memories/builder-error.log
=> MediaWiki: Add relevant wikimedia/wikipedia related projects

cfg/projects/aMule.json
=> aMule: fix project URL

cfg/projects/AuroraStore.json, cfg/projects/F-Droid.json, cfg/projects/Penpot.json
Per completar els canvis de @rbnval (gràcies!)
A més adapto l'estil dels fitxers (espais)
=> Add licenses to AuroraStore, F-Droid and Penpot

cfg/projects/MyPaint.json, cfg/projects/Ubuntu.json
MyPaint: change website project
Ubuntu: fix repo for ubiquity-slideshow file
=> Fix projects: MyPaint and Ubuntu

cfg/projects/JClic.json, cfg/projects/Scilab.json
JClic: update projectweb
Scilab: fix link to retrieve translation files
=> Fix JClic and Scilab projects

cfg/projects/SMPlayer.json, cfg/projects/Scribus.json, cfg/projects/Subsurface.json, cfg/projects/yumex.json
Aquests crec que no acaben de funcionar. La sortida és:
```
$ python3 builder.py -pSMPlayer
Translation memory builder version 0.1
Use --help for assistance
Projects defined in the projects configuration directory 224
processing 1 files...
[###########################################] 100%
Projects. Added into tots-tm.po a total of 0 words from 0 projects. Skipped 1 with 8376 words
Projects clean up:0
processing 1 files...
[###########################################] 100%
SMPlayer project. 1715 translated strings, words 8376
Project.get_words_entries exception output/tots-tm.po
Translation memory project. -1 translated strings, words -1
Time used to build memories: 0:00:01.179229
MACQG9CTF7QW2:src pere$ python3 builder.py -pScribus
Translation memory builder version 0.1
Use --help for …
```
=> Draft: move 4 projects from Transifex

cfg/projects/Dino.json, cfg/projects/StickyNotes.json
Són projectes petits però que estan mantinguts
=> Add Dino and Sticky Notes projects

cfg/projects/Element.json
Veure https://github.com/Softcatala/translation-memory-tools/pull/279#issuecomment-1673548280
=> fix(Element): remove repos without a translation

cfg/projects/OrganicMaps.json
Fa servir un format una mica peculiar (twine): https://github.com/pereorga/software-translations/blob/master/organicmaps/generate.sh
=> Organic Maps: new project

cfg/projects/WindowsCalculator.json
He afegit un fitxer de traducció i he aprofitat per moure el directori
=> refactor(mscalc): switch to git type and patterns

cfg/projects/OBSStudio.json, src/builder/convertfiles.py
1. He hagut d'afegir nous patrons de noms de fitxers ini
2. No he pogut afegir el nom del projecte amb espais (la importació fallava)
=> OBS Studio: new project

cfg/projects/Qalculate.json
He intentat afegir el fitxer TS també, de https://raw.githubusercontent.com/Qalculate/qalculate-qt/main/translations/qalculate-qt_ca.ts
Però sembla que no és compatible amb `ts2po`:
```
ts2po qalculate-qt_ca.ts
ts2po: WARNING: Error processing: input qalculate-qt_ca.ts, output None, template None: cannot access local variable 'messagenum' where it is not associated with a value
```
=> Qalculate: new project

cfg/projects/AsteroidOS.json
La llista de repositoris de l'AsteroidOS és probablement massa llarga per mantenir-la individualment:
https://hosted.weblate.org/projects/asteroidos/
=> refactor(asteriodos): switch to single Weblate entry

cfg/projects/OnlyOffice.json
Importa unes 30.000 paraules.
Potser el més rellevant que falta és https://github.com/ONLYOFFICE/desktop-apps/blob/master/macos/Localization/ca.xliff, que `xliff2po` converteix 100% a cadenes "fuzzy". Tinc pendent una PR per aquest tema.
=> OnlyOffice: new project

cfg/projects/MythTV.json
Depèn de https://github.com/translate/translate/pull/4987 o equivalent
=> MythTV: new project

cfg/projects/LocalSend.json, src/builder/convertfiles.py
Afegeix els noms "strings.i18n.json" i "strings_ca.i18n.json"
=> LocalSend: new project

cfg/projects/FreeTube.json
Utilitzo yaml2po. Suposo que es podria integrar de forma semblant a com ho fem amb els fitxers JSON (el que potser estaria relacionat amb https://github.com/Softcatala/translation-memory-tools/issues/338):
https://github.com/pereorga/software-translations/blob/master/freetube/generate.sh
Tampoc sembla que sigui un format gaire usat
=> FreeTube: new project

cfg/projects/WordPress-plugins.json
Han migrat a una plataforma de traducció privada: https://yoast.com/help/can-i-contribute-to-the-translation-of-the-plugin/
També tinc dubtes sobre la llicència
=> Yoast SEO plugin Premium: delete translation file

cfg/projects/phpMyAdmin.json
Remove two extra files to avoid network problems
=> Adjusting configuration for phpMyAdmin project

cfg/projects/Bitcoin.json
Script: https://github.com/pereorga/software-translations/blob/master/bitcoin/generate.sh
Context: https://github.com/Softcatala/translation-memory-tools/pull/270
=> Bitcoin: move to custom repository

cfg/projects/AnnasArchive.json
El seu Weblate ara demana autenticació
=> Anna's Archive: switch to raw file from GitLab

cfg/projects/Fossify.json
Fork de l'antic [Simple Mobile Tools](https://github.com/SimpleMobileTools)
=> Fossify: new project

cfg/projects/YouApps.json
Autorecordatori: integrar també https://github.com/you-apps/TranslateYou/pull/399
=> You Apps: new projects

cfg/projects/DAVx5.json
Keep track DAVx5 project from git repo
=> Add DAVx5 project

cfg/projects/SugarLabs.json
Move SugarLabs project from Transifex to Github and fix repo paths
=> Fix SugarLabs project

src/builder/convertfiles.py
As per https://github.com/localsend/localsend/commit/6391364dca7e2490db57306aa79fd18887fa1337
=> fix(localsend): add new JSON filename pattern 

cfg/projects/Qgis.json
Sembla que la web ja no es tradueix
=> Qgis: remove old website project

cfg/projects/YunoHost.json
YunoHost: Remove a missing item and added new items
=> Fix YunoHost project configuration
